[theme]
primaryColor="#F63366"  # Example: Change to your desired primary color
backgroundColor="#FFFFFF"  # Set your desired background color
secondaryBackgroundColor="#F0F2F5"
textColor="#000000"      # This ensures all text will be black
font="sans serif"